### ISSUE TITLE
Training examples 

### ISSUE THREAD

**Issue by drcege** [PengBoXiangShang/torchsketch#2]
Coule you provide some training/testing scripts to demonstrate practical usage? -- reproduce results in the survey

It seems that the project is still under development, am i right? If so, may be better to have a roadmap to let people know which modules are done and which parts are currently unstable.

**Comment by yael-vinker** [comment]
Hi, any updates regarding this ? could you please upload some training/testing scripts ?
Otherwise, it is hard to use and reproduce the results
