### ISSUE TITLE
what are coordinate files?

### ISSUE THREAD

**Issue by JunYoungOH97** [PengBoXiangShang/torchsketch#3]
I downloaded the quickdraw data using torchsketch.
(torchsketch.data.datasets.quickdraw.quickdraw_414k.download_quickdraw_414k.py)

The downloaded folder was as follows.
1. picture_files
2. coordinate_files

Of these two, "2. coordinate_files" were difficult to understand.
The format was "npy" and when printed through "np.load", the results were as follows.

- print(data) :
[[  0. 246.   1.   0.]
 [ 25. 186.   1.   0.]
 [ 63. 120.   1.   0.]
 [ 81.  83.   1.   0.]
 [101.  37.   1.   0.]
  ...
 [-1, -1, -1, -1]
  ...
 [-1, -1, -1, -1]]

- print(data.shape) :
(100, 4)

Can you explain each [a, b, c, d] here?
(e.g. [0, 246, 1, 0])

**Comment by PengBoXiangShang** [comment]
each numpy array (100 x 4) denotes 100 key points of a sketch.
each point is a 4-d vector [x, y, 1, 0] or [x, y, 0, 1], 
x and y are coordinates. the 3rd and 4th bits are flat bits. 
[x, y, 0, 1] means key point (x, y) is the ending point on its stroke.

the simple sketches (less then 100 key points) will be padded by [-1, -1, -1, -1].

**Comment by JunYoungOH97** [comment]
Thank you for your detailed explanation!
Thanks to you, I learned a lot.
Good luck!

> each numpy array (100 x 4) denotes 100 key points of a sketch.
> each point is a 4-d vector [x, y, 1, 0] or [x, y, 0, 1],
> x and y are coordinates. the 3rd and 4th bits are flat bits.
> [x, y, 0, 1] means key point (x, y) is the ending point on its stroke.
> 
> the simple sketches (less then 100 key points) will be padded by [-1, -1, -1, -1].
