### ISSUE TITLE
Thanks, image-> sketch capabilities (rtsc available)?

### ISSUE THREAD

**Issue by albertotono** [PengBoXiangShang/torchsketch#4]
Thank you so much for this great repo, 
I was wondering if you have any plans to implement rtsc for converting also image to sketch with different techniques? 
https://rtsc.cs.princeton.edu/  or neural contourns or other? 

Do you know if there is already a repository for these converstions?

Great work and thanks

**Comment by PengBoXiangShang** [comment]
https://openaccess.thecvf.com/content_cvpr_2018/papers/Song_Learning_to_Sketch_CVPR_2018_paper.pdf
Hello, you may want to check this project.
